.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "BACON" "1" "April 2014" "" ""
.
.SH "NAME"
\fBbacon\fR \-\- Command line Baconian Cipher utility
.
.SH "SYNOPSIS"
\fBbacon\fR [\-hV] <command> [alpha]
.
.SH "OPTIONS"
  \-V, \-\-version
      output program version
.
.P
  \-h, \-\-help
      output help information
.
.SH "INPUT"
  [alpha]
      cipher alphabet\. Default: \'ABCDEFGHIKLMNOPQRSTUWXYZ\'
.
.SH "COMMANDS"
  \fBencode\fR
      Encode stdin stream
.
.P
  \fBdecode\fR
      Decode stdin stream
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Joseph Werle \fIjoseph\.werle@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/libbacon/issues\fR
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/libbacon\fR
.
.IP "\(bu" 4
\fIhttps://github\.com/mathiasbynens/bacon\-cipher\fR
.
.IP "" 0
.
.SH "LICENSE"
MIT